package com.employee.enums;

public enum CategoryType {
    SANITY_POST_CALL, SMOKE_POST_CALL, REGRESSION_POST_CALL, END_TO_END_POST_CALL, MINI_REGRESSION_POST_CALL,
    SANITY_GET_CALL, SMOKE_GET_CALL, REGRESSION_GET_CALL, END_TO_END_GET_CALL, MINI_REGRESSION_GET_CALL, REGRESSION;
}
